[package]
name = "nazmc_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "*"
documented = "*"
strum = { version = "*", features = ["derive"] }
nazmc_data_pool = { path = "../nazmc_data_pool" }
nazmc_diagnostics = { path = "../nazmc_diagnostics" }
